Fix NoClassDefFoundError when simple-voice-chat is missing
Moved VoicechatCompat to VoicechatImpl and added a facade for VoicechatCompat to avoid loading SVC classes natively unless required.